[DopplerSegmentator]
path=D:/kuba/doppler_segmentator.exe
model_path=./model_21/model_cfg.ini

[JadraSegmentator]
; Konfiguracja przykładowa dla machine 2 (desktop)
python_path = C:/Users/meow/anaconda3/python.exe
script_path = python/JadraKostnienia/src/run_jadra_pipeline.py
config_path = D:/data/JadraKostnienia2026/JadraKostnienia/experiments/experiment_001/resolved_config.yaml
checkpoint_path = D:/data/JadraKostnienia2026/JadraKostnienia/experiments/experiment_001/checkpoints/best_checkpoint.pth

